# Build Job to be used between main and pages workflows
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  # Reusable Workflow
  workflow_call:

    inputs:
      # Run end to end tests
      test:
        required: false
        type: boolean
        default: false

      # Upload built files as static artifact
      upload:
        required: false
        type: boolean
        default: false

jobs:
  build:
    timeout-minutes: 10
    # Match Development Operating System
    runs-on: ubuntu-latest
    steps:

    # Setup
    - uses: actions/checkout@v4
  
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        # Match Development Node Version
        node-version: '22.x'

    # Tool Versions
    - name: Node Version
      run: node --version

    - name: NPM Version
      run: npm --version

    # Package Setup
    - name: clean install
      run: npm ci

    # 'npm run build' broken into separate steps
    - name: clean
      run: npm run clean

    - name: style
      run: npm run style-check

    - name: spell-check
      run: npm run spell-check --if-present

    - name: lint
      run: npm run lint

    - name: compile
      run: npm run compile
